# Generated by Django 6.0.3 on 2026-03-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_ad_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
