# Generated by Django 6.0.3 on 2026-04-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_onetimecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое статьи'),
        ),
    ]
