# Generated by Django 6.0.3 on 2026-04-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_ad_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='ads_documents/', verbose_name='Документ'),
        ),
    ]
