# Generated by Django 6.0.3 on 2026-04-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_ad_document'),
        ('board', '0007_alter_response_unique_together'),
    ]

    operations = [
    ]
